# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

FROM docker-hub.repo.splunkdev.net/ubuntu:22.10

COPY clang-format /root/clang-format

WORKDIR /root
ENTRYPOINT ["/root/clang-format"]


